---
exampleValuesSNVrange:
  note: "Example for EIF4A1 transcript region matches (precise variants)"
  label: "SNV Range Example"
  description: |
    As in the standard SNV query, this example shows a Beacon query against
    mutations in the EIF4A1 gene in the DIPG childhood brain tumor dataset.
    However, this range + wildcard query will return any variant with a *single*
    alternate base (indicated through "N").
    The exact variants which were being found can be retrieved through the variant
    handover [H—>O] link.
  parameters:
    datasetIds: 
      examplevalue: "dipg"
    includeDatasetResponses:
      examplevalue: "ALL"
      visibility: "hide"    
    assemblyId: 
      examplevalue: "GRCh38"
    geneinputField: 
      examplevalue: "EIF4A1"
    referenceName: 
      examplevalue: 17
    start: 
      examplevalue: ""
    end: 
      examplevalue: ""
    startMin: 
      examplevalue: 7572826
    startMax: 
      examplevalue: ""
    endMin: 
      examplevalue: ""
    endMax: 
      examplevalue: 7579005
    variantType: 
      examplevalue: ""
    alternateBases: 
      examplevalue: "N"
    referenceBases: 
      examplevalue: "N"
  ontology_queries:
    - "NCIT"
    - "icdom"
    - "icdot"

exampleValuesSNV:
  note: "Example for specific EIF4A1 mutation"
  label: "SNV Example"
  description: |
    This example shows a core Beacon query, against a specific
    mutation in the EIF4A1 gene, in the DIPG childhood brain tumor dataset.
  parameters:
    datasetIds: 
      examplevalue: "dipg"
    includeDatasetResponses:
      examplevalue: "ALL"
      visibility: "hide"    
    assemblyId: 
      examplevalue: "GRCh38"
    geneinputField: 
      examplevalue: "EIF4A1"
      visibility: "hide"
    cytoinputField: 
      examplevalue: ""
    referenceName: 
      examplevalue: 17
    start: 
      examplevalue: 7577121
    end: 
      examplevalue: ""
    startMin: 
      examplevalue: ""
    startMax: 
      examplevalue: ""
    endMin: 
      examplevalue: ""
    endMax: 
      examplevalue: ""
    variantType: 
      examplevalue: ""
    alternateBases: 
      examplevalue: "A"
    referenceBases: 
      examplevalue: "G"
    materialtype:
      examplevalue: ""
      visibility: "hide"
    freeFilters:
      examplevalue: ""
      visibility: "hide"
  ontology_queries:
    - "icdot-C71.7"
    - "NCIT"
    - "icdom"
    - "icdot"

