---
exampleValuesCNV:
  note: "Example for focal CDKN2A deletion matches."
  label: "CNV Example"
  description: |
    This example shows the query for CNV deletion variants overlapping the
    CDKN2A gene's coding region with at least a single base, but limited
    to "focal" hits (here i.e. <= ~4Mbp in size). The query is against the
    arrayMap collection and can be modified e.g. through changing the position
    parameters or data source.
  parameters:
    datasetIds: 
      examplevalue: "arraymap"
    includeDatasetResponses:
      examplevalue: "ALL"
      visibility: "hide"    
    assemblyId: 
      examplevalue: "GRCh38"
    geneinputField: 
      examplevalue: "CDKN2A"
    referenceName: 
      examplevalue: 9
    start: 
      examplevalue: ""
    end: 
      examplevalue: ""
    startMin: 
      examplevalue: 20000001
    startMax: 
      examplevalue: 21975098
    endMin: 
      examplevalue: 21967753
    endMax: 
      examplevalue: 23000000
    variantType: 
      examplevalue: "DEL"
    alternateBases: 
      examplevalue: ""
      visibility: "hide"
    referenceBases: 
      examplevalue: "N"
      visibility: "hide"
    freeFilters:
      examplevalue: "" # "geolat:49,geolong:8.69,geodist:2000000"
    materialtype:
      examplevalue: "" #"EFO:0009656"
      visibility: "hide"
    freeFilters:
      examplevalue: ""
      visibility: "hide"
  ontology_queries:
    - "icdom-94403"
    - "icdom"

exampleValuesSNVrange:
  note: "Example for EIF4A1 transcript region matches (precise variants)"
  label: "SNV Range Example"
  description: |
    As in the standard SNV query, this example shows a Beacon query against
    mutations in the EIF4A1 gene in the DIPG childhood brain tumor dataset.
    However, this range + wildcard query will return any variant with a *single*
    alternate base (indicated through "N").
    The exact variants which were being found can be retrieved through the variant
    handover [H—>O] link.
  parameters:
    datasetIds: 
      examplevalue: "dipg"
    includeDatasetResponses:
      examplevalue: "ALL"
      visibility: "hide"    
    assemblyId: 
      examplevalue: "GRCh38"
    geneinputField: 
      examplevalue: "EIF4A1"
    referenceName: 
      examplevalue: 17
    start: 
      examplevalue: ""
    end: 
      examplevalue: ""
    startMin: 
      examplevalue: 7572826
    startMax: 
      examplevalue: ""
    endMin: 
      examplevalue: ""
    endMax: 
      examplevalue: 7579005
    variantType: 
      examplevalue: ""
    alternateBases: 
      examplevalue: "N"
    referenceBases: 
      examplevalue: "N"
  ontology_queries:
    - "NCIT"
    - "icdom"
    - "icdot"

exampleValuesSNV:
  note: "Example for specific EIF4A1 mutation"
  label: "SNV Example"
  description: |
    This example shows a core Beacon query, against a specific
    mutation in the EIF4A1 gene, in the DIPG childhood brain tumor dataset.
  parameters:
    datasetIds: 
      examplevalue: "dipg"
    includeDatasetResponses:
      examplevalue: "ALL"
      visibility: "hide"    
    assemblyId: 
      examplevalue: "GRCh38"
    geneinputField: 
      examplevalue: "EIF4A1"
      visibility: "hide"
    cytoinputField: 
      examplevalue: ""
    referenceName: 
      examplevalue: 17
    start: 
      examplevalue: 7577121
    end: 
      examplevalue: ""
    startMin: 
      examplevalue: ""
    startMax: 
      examplevalue: ""
    endMin: 
      examplevalue: ""
    endMax: 
      examplevalue: ""
    variantType: 
      examplevalue: ""
    alternateBases: 
      examplevalue: "A"
    referenceBases: 
      examplevalue: "G"
    materialtype:
      examplevalue: ""
      visibility: "hide"
    freeFilters:
      examplevalue: ""
      visibility: "hide"
  ontology_queries:
    - "icdot-C71.7"
    - "NCIT"
    - "icdom"
    - "icdot"

exampleValuesClinVar:
  note: "Example for TP53 mutation (ClinVar annotated) in a cell line"
  label: "ClinVar Example"
  description: |
    This example shows a core Beacon query, against a specific
    mutation in the TP53 gene, in cellosaurus, with ClinVar data.
  parameters:
    datasetIds: 
      examplevalue: "cellosaurus"
    includeDatasetResponses:
      examplevalue: "ALL"
      visibility: "hide"    
    assemblyId: 
      examplevalue: "GRCh38"
    geneinputField: 
      examplevalue: "TP53"
    cytoinputField: 
      examplevalue: "17p13.1"
    referenceName: 
      examplevalue: 17
    start: 
      examplevalue: 7673767
    end: 
      examplevalue: ""
    startMin: 
      examplevalue: ""
    startMax: 
      examplevalue: ""
    endMin: 
      examplevalue: ""
    endMax: 
      examplevalue: ""
    variantType: 
      examplevalue: ""
    alternateBases: 
      examplevalue: "T"
    referenceBases: 
      examplevalue: "C"
    materialtype:
      examplevalue: ""
      visibility: "hide"
    freeFilters:
      examplevalue: ""
      visibility: "hide"
  ontology_queries:
    - "NCIT"
      
#exampleValuesBND:
#  note: "Breakpoint Queries (e.g. BND or CNV edges)."
#  label: "BND Example"
#  description: |
#    For this example the arrayMap collection is queried for samples
#    with a breakpoint/fusion event around the MYC gene.
#    Additionally to "BND" annotations, also the ends of "DUP" and "DEL"
#    events are being considered internally.
#  parameters:
#    datasetIds: 
#      examplevalue: "arraymap"
#    assemblyId: 
#      examplevalue: "GRCh38"
#    geneinputField: 
#      examplevalue: ""
#    referenceName: 
#      examplevalue: 8
#    start: 
#      examplevalue: ""
#    end: 
#      examplevalue: ""
#    startMin: 
#      examplevalue: 127500000
#    startMax: 
#      examplevalue: 127900000
#    endMin: 
#      examplevalue: ""
#    endMax: 
#      examplevalue: ""
#    variantType: 
#      examplevalue: "BND"
#    alternateBases: 
#      examplevalue: ""
#      visibility: "hide"
#    referenceBases: 
#      examplevalue: "N"
#      visibility: "hide"
#  ontology_queries:
#    - "icdom-80703"
#    - "NCIT"
#    - "icdom"
#    - "icdot"


