---
variantAlleleRequest:
  note: "Example for specific EIF4A1 mutation"
  label: "Allele Request"
  description: |
    The <i>Beacon Allele Request</i> corresponds to the original Beacon query, in which
    variants with a specific combination of reference and alternate bases are being
    matched. "N" here can stand in as wildcard nucleotide.
  parameters:
    datasetIds: 
      placeholder: "dipg"
    includeDatasetResponses:
      placeholder: "ALL"
      visibility: "hide"    
    requestType:
      value: "variantAlleleRequest"
      visibility: "hide"
    assemblyId: 
      placeholder: "GRCh38"
    geneinputField: 
      placeholder: ""
      visibility: "hide"
    cytoinputField: 
      placeholder: ""
      visibility: "hide"    
    referenceName: 
      placeholder: 17
    start: 
      placeholder: 7577121
    startMax: 
      placeholder: ""
      visibility: "hide"    
    endMin: 
      placeholder: ""
      visibility: "hide"    
    end: 
      placeholder: ""
      visibility: "hide"
    variantType: 
      placeholder: ""
      visibility: "hide"    
    alternateBases: 
      placeholder: "A"
    referenceBases: 
      placeholder: "G"
    materialtype:
      placeholder: ""
      visibility: "hide"
    freeFilters:
      placeholder: ""
      visibility: "hide"
  ontology_queries:
    - "icdot-C71.7"
    - "NCIT"
    - "icdom"
    - "icdot"

variantCNVrequest:
  note: ""
  label: "CNV Request"
  description: |
    This query type is for copy number queries ("variantCNVrequest"), e.g. using fuzzy
    ranges for start and end positions to capture a set of similar variants.
  parameters:
    datasetIds: 
      placeholder: ""
    includeDatasetResponses:
      placeholder: "ALL"
      visibility: "hide"
    requestType:
      value: "variantCNVrequest"
      visibility: "hide"
    assemblyId: 
      placeholder: "GRCh38"
    geneinputField: 
      placeholder: "CDKN2A"
      visibility: "hide"
    cytoinputField: 
      placeholder: ""
      visibility: "hide"    
    referenceName: 
      placeholder: 9
    start: 
      placeholder: 19000001
    startMax: 
      placeholder: 21975098
    endMin: 
      placeholder: 21967753
    end: 
      placeholder: 24000000
    variantType: 
      placeholder: "DEL"
      visibility: "hide"
    alternateBases: 
      placeholder: ""
      visibility: "hide"
    referenceBases: 
      placeholder: "N"
      visibility: "hide"
    freeFilters:
      placeholder: "" # "geolat:49,geolong:8.69,geodist:2000000"
    materialtype:
      placeholder: "" #"EFO:0009656"
      visibility: "hide"
    freeFilters:
      placeholder: ""
      visibility: "hide"

variantRangeRequest:
  note: ""
  label: "Range Query"
  description: |
    Range + wildcard query will return any variant between the given positions. Either a
    "variant type" or alternate bases ("N" for wildcard) should be specified.
    The exact variants which were being found can be retrieved through the variant
    handover [H—>O] link.
  parameters:
    datasetIds: 
      placeholder: ""
    includeDatasetResponses:
      placeholder: "ALL"
      visibility: "hide"    
    requestType:
      value: "variantRangeRequest"
      visibility: "hide"
    assemblyId: 
      placeholder: "GRCh38"
    geneinputField: 
      placeholder: ""
      visibility: "hide"    
    cytoinputField: 
      placeholder: ""
      visibility: "hide"    
    referenceName: 
      placeholder: 17
    start: 
      placeholder: 7572826
    startMax: 
      placeholder: ""
      visibility: "hide"
    endMin: 
      placeholder: ""
      visibility: "hide"
    end: 
      placeholder: 7579005
    variantType: 
      placeholder: ""
    alternateBases: 
      placeholder: "N"
    referenceBases: 
      placeholder: "N"

emptyRequest:
  note: ""
  label: "All Fields"
  description: |
    All form fields for composing your own queries.
  parameters:
    datasetIds: 
      placeholder: ""
    includeDatasetResponses:
      placeholder: "ALL"
    requestType:
      value: ""
    assemblyId: 
      placeholder: "GRCh38"
    geneinputField: 
      placeholder: "CDKN2A"
    cytoinputField: 
      placeholder: "9p13.1"
    referenceName: 
      placeholder: 9
    start: 
      placeholder: 19000001
    startMax: 
      placeholder: 21975098
    endMin: 
      placeholder: 21967753
    end: 
      placeholder: 24000000
    variantType: 
      placeholder: "DEL"
    alternateBases: 
      placeholder: "A"
    referenceBases: 
      placeholder: "G"
    freeFilters:
      placeholder: "" # "geolat:49,geolong:8.69,geodist:2000000"
    materialtype:
      placeholder: "" #"EFO:0009656"
    freeFilters:
      placeholder: ""

